#!/bin/bash
rpmbuild --define "_source_filedigest_algorithm 1" \
         --define "_binary_filedigest_algorithm 1" \
         --define "_binary_payload w9.gzdio" \
         --define "_source_payload w9.gzdio" \
         --define "_default_patch_fuzz 2" "$@"
